In [4]:
import pandas as pd

In [ ]:
# !pip install mysql-connector-python

In [ ]:
df_cust = pd.read_csv("dataset/customers.csv")
df_cust.head()

In [ ]:
df_cs = pd.read_csv("dataset/credit_profiles.csv")
df_cs.head()

In [ ]:
df_trans = pd.read_csv("dataset/transactions.csv")
df_trans.head()

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host='localhost',
    user='root',
    passwd='root',
    database='e_master_card'
)

df_cust = pd.read_sql("SELECT * FROM customers", conn)
df_cust.head(3)

In [ ]:
df_cust = pd.read_sql("SELECT * FROM customers", conn)
df_cust.head(3)

In [1]:
import pymysql

conn = pymysql.connect(
    host="127.0.0.1",
    user="root",
    password="root",
    database="e_master_card",
    port=3306
)

print("Connected")

Connected

In [7]:
df_cust = pd.read_sql("SELECT * FROM customers", conn)
df_cust.head()

C:\Users\Yogesh Kshirsagar\AppData\Local\Temp\ipykernel_15960\1487446849.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cust = pd.read_sql("SELECT * FROM customers", conn)

,cust_id,name,gender,age,location,occupation,annual_income,marital_status
0,1,Dhruv Bansal,Female,2,City,Business Owner,358211.0,Married
1,2,Kabir Thakur,Female,47,City,Consultant,65172.0,Single
2,3,Kriti Mangal,Male,21,City,Freelancer,22378.0,Married
3,4,Sara Dwivedi,Male,24,Rural,Freelancer,33563.0,Married
4,5,Aarohi Negi,Male,48,City,Consultant,39406.0,Married

In [8]:
df_transactions = pd.read_sql("SELECT * FROM transactions", conn)
df_transactions.head()

C:\Users\Yogesh Kshirsagar\AppData\Local\Temp\ipykernel_15960\784827632.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_transactions = pd.read_sql("SELECT * FROM transactions", conn)

,tran_id,cust_id,tran_date,tran_amount,platform,product_category,payment_type
0,1,705,2023-01-01,63,Flipkart,Electronics,Phonepe
1,2,385,2023-01-01,99,Alibaba,Fashion & Apparel,Credit Card
2,3,924,2023-01-01,471,Shopify,Sports,Phonepe
3,4,797,2023-01-01,33,Shopify,Fashion & Apparel,Gpay
4,5,482,2023-01-01,68,Amazon,Fashion & Apparel,Net Banking

In [9]:
df_cs = pd.read_sql("SELECT * FROM credit_profiles", conn)
df_cs.head()

C:\Users\Yogesh Kshirsagar\AppData\Local\Temp\ipykernel_15960\1858606683.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cs = pd.read_sql("SELECT * FROM credit_profiles", conn)

,cust_id,credit_score,credit_utilisation,outstanding_debt,credit_inquiries_last_6_months,credit_limit
0,1,749,0.585171,19571.0,0.0,40000.0
1,2,587,0.107928,161644.0,2.0,1250.0
2,3,544,0.854807,513.0,4.0,1000.0
3,4,504,0.336938,224.0,2.0,1000.0
4,5,708,0.586151,18090.0,2.0,40000.0